# Generated by Django 5.1.3 on 2024-11-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custreq',
            name='usid',
            field=models.IntegerField(default=0),
        ),
    ]
