# Generated by Django 5.1.3 on 2024-11-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0002_custreq_usid'),
    ]

    operations = [
        migrations.AddField(
            model_name='custreq',
            name='stat',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
