# Generated by Django 5.1.3 on 2024-12-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0003_custreq_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='custreq',
            name='reqid',
            field=models.IntegerField(default=0),
        ),
    ]
